### ISSUE TITLE
Incompatibility with Bloodmoon

### ISSUE THREAD

**Issue by CalaMariGold** [Fuzss/let-me-sleep#1]
Bloodmoon is a popular mod that disables sleeping during a Bloodmoon. Sleeping can not occur during that time or else it defeats the whole purpose.

When Let Me Sleep is installed, it overrides that and well... lets you sleep (curse you clever name). It would be absolutely amazing if some kind of compatibility was formed so that sleeping is still disabled during a bloodmoon. At the moment, I can not keep Let Me Sleep as Bloodmoon is too important, as I'm sure many other people feel too.

Thank you for reading and I hope you consider this!

**Comment by Fuzss** [comment]
Fixed in 6dd9cef, will release in a couple of days as part of v1.2 on Curse.
