### ISSUE TITLE
1.12.2 Compatibility with Comforts Sleeping Bag?

### ISSUE THREAD

**Issue by ghost** [Fuzss/let-me-sleep#11]
Is there a chance to disallow the Letmesleep methods for setting Spawnpoints with the Comfort mod Sleeping Bag?

The Sleeping Bag allows you to sleep, but doesn't let you set your spawn point. It's a great item.

However, with Let me Sleep installed, most (if not all) of the config options for setting a respawn point occur when using a Sleeping Bag, despite the fact that Sleeping Bags shouldn't reset the spawn point.

**Comment by Fuzss** [comment]
1.12 isn't supported anymore, I'm only considering hotfixes really.
I'd recommend setting the `Set Respawn Point` option to something that at least doesn't force the spawn point to be set every time, so sleeping bags may still be used as they're intended to.
