### ISSUE TITLE
A new Config type with name "Sleeptime" for the 1.12.2 Version. (What it can in the description here)

### ISSUE THREAD

**Issue by Titoo8899** [Fuzss/let-me-sleep#14]
hi,
I have a cool idear for a new configthink of your mod with a cool system. 
Name:     "Sleeptime". 
Function: With Sleeptime can you say from 0-24000 how long you will sleep then you go in a bed.
 
2 Example:
  1 - I make in the Config "2000" = "2 Hours" ingametime 6:00 and then I go to bed and sleep I wake Up on 8:00 and then I 
       now go to bed a second time the Clock say 8:00 Begin who I go in the bed and I wake up 10:00.

 2 - I make in the Config "8000" = "8 Hours" ingametime 6:00 and then I go to bed and sleep I wake Up on 14:00 and then I 
       now go to bed a second time the Clock say 14:00 Begin who I go in the bed and I wake up 22:00.

It i not the Config of "Wake Up Time" this Config from you say I will on this time wake up in confit is "2000" = 8:00 but I will only in stages sleep and not a full day or so sleep. I hope you can so a Config ad in 1.12.2

**Comment by Titoo8899** [comment]
I hope my description help you to make this new Config.

**Comment by Fuzss** [comment]
1.12 is no longer supported, most recent update was just a hotfix.
A similar feature is planned for future versions on 1.17 probably though.

**Comment by Titoo8899** [comment]
oh okay, I have hope so a feature in 1.12.2 to become. I found not so good mods for so what. And the most of this was on serverside mods and your mod work on server and client and I have hope you can so what add in the 1.12.2.

**Comment by Titoo8899** [comment]
Can you please one last update make in the future for 1.12.2 with so a feature?
