### ISSUE TITLE
Comforts Incompatability

### ISSUE THREAD

**Issue by IdrisQe** [Fuzss/let-me-sleep#3]
Edit: Whoops I accidentally hit enter too early and didn't type anything.

The "Set Respawn Point" option, when set to Interact, is incompatible with Comforts Sleeping Bags, as they don't set your spawn, so instead of setting your spawn then being able to sleep, they infinitely say "Spawnpoint set" whenever you click them. Also, the "automatically use sleeping bags" option in Comforts doesn't apply. This is likely the same case with hammocks.

**Comment by Fuzss** [comment]
1.12 isn't supported anymore unfortunately.
