### ISSUE TITLE
[Suggestion] Allow for custom monsters to spawn with cfg

### ISSUE THREAD

**Issue by sanedsf** [Fuzss/let-me-sleep#6]
This is exactly the type of mod I am looking for and it is awesome.
I am using the 1.12.2 version of the mod.
With the latest forge for that version (14.23.5.2847).

I am wondering if there is a way to add an option in order to spawn custom mobs specified in the config file.
I noticed that in this line [line](https://github.com/Fuzss/letmesleep/blob/dc2864d42ae43ecf9ab3a17f8bbb3d5fc08ce934/src/main/java/com/fuzs/letmesleep/handler/BadDreamHandler.java#L86) you are getting a random monster in the dungeonhooks that are registered. But what about mobs not on that list or are passive?

For example I would like to spawn a couple of Sirens from Ice and Fire plus/or 3-4 silverfish. (ID = iceandfire:siren)

Thank you very much for your hard work!

**Comment by Fuzss** [comment]
Added in v1.3b1 for 1.16. Will be backported for 1.15 eventually, but not for 1.12.
