### ISSUE TITLE
Server Crash on waking up.

### ISSUE THREAD

**Issue by Sereath** [Fuzss/let-me-sleep#8]
Player joins, places a bed, goes to sleep and the server crashes as soon as he wakes up.

LetMeSleep-v1.2.1-1.12.2

forge-1.12.2-14.23.5.2854

[crash-2020-12-27_02.25.39-server.txt](https://github.com/Fuzss/letmesleep/files/5744289/crash-2020-12-27_02.25.39-server.txt)

**Comment by Fuzss** [comment]
Fixed in v1.2.2.
