### ISSUE TITLE
Null bed coordinates crash

### ISSUE THREAD

**Issue by border999** [Fuzss/let-me-sleep#9]
[crash-2021-03-17_16.55.44-server.txt](https://github.com/Fuzss/letmesleep/files/6161166/crash-2021-03-17_16.55.44-server.txt)

**Comment by Fuzss** [comment]
1.12 isn't supported anymore.
This issue won't occur then whens disabling `Always Set Spawn` and setting `Set Respawn Point` to vanilla. You won't be able to use these two features then unfortunately, but at least both mods may work together.
